### ISSUE TITLE
AJAX not working 

### ISSUE THREAD

**Issue by josiase95** [X-Raym/wavesurfer-wp#4]
Hi X-Raym,

Not sure if you're still updating this plugin. I've noticed that it doesn't really work with AJAX anymore 🥹 Hope you'd be able to look into it.

Best,
Jacob

**Comment by X-Raym** [comment]
@jagge72 ajax often need custom code depending the event trigger,
check the doc for this, they are code exemples.

If it doesnt work, then I will advice to use alternative plugin as I dont plan to update or do custom support on it. ^^

Good luck !
